### ISSUE TITLE
OverlayView has wrong position by default on Safari if using getPixelPositionOffset props function

### ISSUE THREAD

**Issue by olzhuk** [JustFly1984/react-google-maps-api#882] opened 2020-05-19 13:39 UTC
# Issue template

Hello!  I have some issue with api on Safari (Chrome, Firefox, Microsoft Edge work good). OverlayView has wrong position by default (getPixelPositionOffset does not work). After scroll map position reset to correct value.

           <OverlayView
            position={coordinate}
            mapPaneName={OverlayView.OVERLAY_MOUSE_TARGET}
            getPixelPositionOffset={(width, height) => (  { x: -width/2, y: -height } )}
          > 
          <button
          className="Button"
          type='button'
          onClick={this.handleButtonClick}
          >
          Test Overlay
          </button>
         </OverlayView>

For map investigation I used code from https://codesandbox.io/s/94o34

## Your Environment

os: mac

react version 16.13.1

@babel version 6.26.0

@react-google-maps/api version 1.9.1

## How is it behave?
OverlayView bottom/center is not over coordinate on Safari. OverlayView position fix after map zooming.
## How should it behave correctly?
OverlayView bottom/center is over coordinate on Safari.

**Comment by JustFly1984** [comment] 2020-05-29 12:10
You can fork a repo and debug. PR is welcome.

**Comment by jacklimwenjie** [comment] 2020-06-23 16:29
I can confirm this happens on Chrome as well. 

@react-google-maps/api version 1.9.7

Google Chrome version 83.0.4103.106

**Comment by JustFly1984** [comment] 2020-06-23 19:30
@jacklimwenjie please provide minimal reproduction in codesandbox.io

**Comment by osphost** [comment] 2020-06-30 09:15
I can also confirm this is happening for me with 1.9.7. I downgraded for now.

**Comment by JustFly1984** [comment] 2020-06-30 10:31
@osphost which version is working correct for you?

**Comment by MindFreeze** [comment] 2020-07-07 08:18
@JustFly1984 I works ok in 1.8.9
I think it broke with this commit https://github.com/JustFly1984/react-google-maps-api/commit/93715fc5a49e1561f9f5996230ed6bd04b1d60ec#diff-11b9b26818f707a9c50c72b5856c935c

**Comment by garretteklof** [comment] 2020-07-26 03:11
What is the workaround / fix for this? I tried downgrading to `1.8.9` and the offset is still not firing on mount (requires a map interaction to 'snap' into place)

**Comment by JustFly1984** [comment] 2020-07-26 10:56
@MindFreeze  @garretteklof if somebody provides PR with fix, I will merge it and release next minor version

**Comment by mjcampagna** [comment] 2020-08-10 23:54
Yeah, `getPixelPositionOffset` isn't working at all. Seems not to be getting called.

**Comment by breeze9527** [comment] 2020-08-11 00:54
I will create a PR to fix it when i have free time.
before it
we can use some hack to "fix" it problem

```tsx

interface Props {
  lat: number;
  lng: number;
}
function MyOverlayView (props: Props) {
  const [_positionInited, setPositionInited] = React.useState(false);
  const position = React.useMemo(() => ({
    lat: props.lat,
    lng: props.lng
  }));
  React.useEffect(() => {
    // use setState to trigger OverlayView's re-render
    setPositionInited(true);
  }, []);
  return (
    <OverlayView
      position={position}
      // ...rest props
    />
  );
}
```

**Comment by JustFly1984** [comment] 2020-08-11 06:26
@breeze9527 useMemo requires second argument.
Where do you use _positionInited in your code? Can you provide minimal reproduction in codesandbox.io please?

**Comment by breeze9527** [comment] 2020-08-11 10:08
> @breeze9527 useMemo requires second argument.
> Where do you use _positionInited in your code? Can you provide minimal reproduction in codesandbox.io please?

The example I just mentioned does not work (that's my mistake, i did not check before comment).
Here is new one: https://codesandbox.io/s/react-google-maps-overlay-view-issue-forked-zl9g4?file=/src/index.js

Goal in example is trigger an additional render after OverlayView load (componentDidMount)

**Comment by mjcampagna** [comment] 2020-08-11 19:23
Thanks, @breeze9527.

We're pushing this back toward the end of our sprint in hopes the library gets a proper fix in quick order. I would very much like to not have to introduce the workaround as tech-debt into our product, though, else I fear it will never be undone.

**Comment by LiniovasDovydas** [comment] 2020-08-19 15:23
Currently as work around for us we redraw the overlay using overlay reference when it loads with a setTimeout of 10ms there's a stutter but it works for now, will investigate further. From what I've quickly seen `this.containerRef` is null on initial `onPositionElement`

`
const ExampleMarker: React.FC = () => {
  const OverlayRef = useRef<OverlayView>();

  const handleOnLoad = () => {
    setTimeout(() => {
      OverlayRef.current.draw();
    }, 10);
  };

  return (
    <OverlayView
      ref={OverlayRef}
      onLoad={handleOnLoad}
      ...
    >
        // Content
    </OverlayView>
  );
});
`

**Closed** 2020-09-01 15:05 UTC

**Comment by mjcampagna** [comment] 2020-09-08 19:19
@JustFly1984 @breeze9527  Thanks for the fix here. Looks like it's not on the 1.9.12 release, though. Any chance you're in a good place to bump the version so that we can pull the update(s) from npm?
