### ISSUE TITLE
Node requirement is the latest version to up

### ISSUE THREAD

**Issue by howdyhyber** [JustFly1984/react-google-maps-api#477] opened 2020-01-30 06:37 UTC
I tried to install the package and yet it requires the latest version of node. Is this necessary?

**Comment by NoiseEee** [comment] 2020-02-04 19:45
This is a change that hes left me in quite a mess!!

**Comment by South-Paw** [comment] 2020-02-09 21:28
Duplicate of #430 - PR (#469) has been merged to address it but is not published

Just roll back to `1.8.1` in lieu of it being published

**Closed** 2021-06-25 12:46 UTC
