### ISSUE TITLE
npm package 2.0.0alpha results in blank map

### ISSUE THREAD

**Issue by derykmarl** [JustFly1984/react-google-maps-api#957] opened 2020-06-09 10:04 UTC
I've just been implementing this map on a gatsby site pulling my hair out :)  Rather than a map I was just getting a grey rectangle.  No errors logged in the JS console.

Steps to reproduce:
Create a very basic gatsby site e.g. based on the hello-world starter then
`npm install @react-google-maps/api`

And a simple index.js page:

```import React from 'react'
import { LoadScript, GoogleMap } from '@react-google-maps/api'

const IndexPage = () => (
  <LoadScript
    googleMapsApiKey="foo"
  >
      <GoogleMap
        mapContainerStyle={{width: "100%", height: "550px"}}
        zoom={16}
        center={{lat: 48.8539241, lng: 2.2913515}}
       />
  </LoadScript>
)
export default IndexPage
```

Comes up blank.

I got it working by uninstalling the package and specifying the previous version:
`npm install @react-google-maps/api@1.9.5`

But I'm not sure why the npm repo is on an alpha version to begin with?

**Comment by JustFly1984** [comment] 2020-06-09 20:30
I do not know why npm offers it as last version, I've marked it as alpha. please do not use alpha version, as it is intended for development only. It is not working version. there will be continuation of support for 1.9.x version until 2.0.0 is going out of alpha. It is very early refactoring for hooks. It definitely has a bug. It will be helpful if community will work on improvements for 2.0.0 version.

**Comment by a-chris** [comment] 2020-06-11 21:25
> I do not know why npm offers it as last version, I've marked it as alpha. please do not use alpha version, as it is intended for development only. It is not working version. there will be continuation of support for 1.9.x version until 2.0.0 is going out of alpha. It is very early refactoring for hooks. It definitely has a bug. It will be helpful if community will work on improvements for 2.0.0 version.

Maybe you can put this warning into the README? Me and my team spent half a day trying to make the 2.0.0 versions works, then I've found this issue and we solved our problems using the 1.9.5 version

**Comment by JustFly1984** [comment] 2020-06-12 07:03
well, alpha version should not has been enabled by default, cos it is.. you know... alpha, it just not in the range of semver. If somebody knows how to move it out of default, and bring back 1.9.5 as default, let me know.

**Comment by cyrfer** [comment] 2020-12-01 16:27
I'm seeing a blank map after I call the Places API. I posted my code over here:
https://github.com/JustFly1984/react-google-maps-api/issues/1338

I am using
```json
"@react-google-maps/api": "^1.13.0",
```

**Comment by JustFly1984** [comment] 2020-12-06 04:07
@cyrfer I think you have issues with components updates. Do you have errors in the console? I'm offering paid services to optimize React applications performance and fix google maps integration. Google maps api is very sensitive to components updates.

**Comment by JustFly1984** [comment] 2020-12-06 05:31
@cyrfer please provide minimal reproduction in codesandbox.io

**Closed** 2020-12-06 05:30 UTC

**Comment by cyrfer** [comment] 2020-12-06 07:30
@JustFly1984  I've had trouble to get the same results in codesandbox.io, but here is the basic app. This demo suffers from a different problem, in that the map loads with a warning from google.
I'd like to hear more about your paid services.
https://codesandbox.io/s/google-maps-places-error-kvirb

**Comment by JustFly1984** [comment] 2020-12-06 16:35
I have upwork account, where I offer my paid services. Send me a private message in Slack. look for invite link in readme.md
