### ISSUE TITLE
MarkerClusterer is broken in latest update

### ISSUE THREAD

**Issue by TrejGun** [JustFly1984/react-google-maps-api#3013] opened 2022-04-30 00:47 UTC
## Please provide an explanation of the issue

My old code throws an error after the last update

```
      <MarkerClusterer
        options={{
          imagePath: "https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m",
        }}
      >
        {(clusterer: Clusterer) =>
          warehouseData.map(warehouse => (
            <MemoMarker
              key={warehouse.Ref}
              position={{
                lat: Number(warehouse.Latitude),
                lng: Number(warehouse.Longitude),
              }}
              clusterer={clusterer}
              onClick={(): void => {
                onSelect(warehouse);
                setWarehouse(warehouse);
              }}
            />
          ))
        }
      </MarkerClusterer>
```

<img width="949" alt="Screen Shot 2022-04-30 at 08 43 37" src="https://user-images.githubusercontent.com/185285/166083783-6caa8fd2-8a2b-4988-95d5-c2bcc251b00e.png">

Not sure how to fix and can't find anything related in the changelog 

## Your Environment

os: mac

node --version
16

react version
17

**Comment by niklashjh** [comment] 2022-05-03 14:02
I have the clusterer working i the latest version, but onClick and other on* props seems to be broken.

**Comment by JustFly1984** [comment] 2022-05-03 16:23
@TrejGun  please try to use F hook based version of component. please look at the source code exports

**Comment by addy** [comment] 2022-05-03 21:19
Since you can't return `JSX.Element[]` from the clusterer function, try wrapping the output in a fragment, like:

```tsx
<MarkerClusterer
    options={{
        imagePath: "https://developers.google.com/maps/documentation/javascript/examples/markerclusterer/m",
    }}
>
    {(clusterer: Clusterer) => (
        <>
            warehouseData.map(warehouse => (
                <MemoMarker
                    key={warehouse.Ref}
                    position={{
                        lat: Number(warehouse.Latitude),
                        lng: Number(warehouse.Longitude),
                    }}
                    clusterer={clusterer}
                    onClick={(): void => {
                        onSelect(warehouse);
                        setWarehouse(warehouse);
                    }}
                />
            ))
        </>
    )}
</MarkerClusterer>
```

**Comment by maddieijams** [comment] 2022-05-03 21:24
This works by adding the fragment to return the single jsx element, but there is a new warning caused by the clusterer
<img width="475" alt="Screen Shot 2022-05-03 at 2 21 19 PM" src="https://user-images.githubusercontent.com/45693734/166568914-a5ce4cb2-81ca-4e34-b495-ac6823d2ed0d.png">

**Comment by TrejGun** [comment] 2022-05-04 02:20
@JustFly1984 sorry, what is F hook? I feel completely lost. please point me to the docs

@addy seems like it works

**Comment by JustFly1984** [comment] 2022-05-04 04:51
@TrejGun If you look at latest commits in the repo - I've created multiple new functional hook components in last version.

Instead of Circle you can import CircleF, etc.

**Comment by fde312** [comment] 2022-05-10 12:36
Adding a fragment solved the typescript error for me. But hover or click event does not work anymore using the latest version v2.10.2.
Had no problems with v2.8.1.

**Comment by JustFly1984** [comment] 2022-05-27 16:59
Please check latest version

**Comment by TrejGun** [comment] 2022-05-27 23:18
still does not work
you can check here https://github.com/TrejGun/trejgun-nova-poshta-google-maps

**Comment by JustFly1984** [comment] 2022-05-31 06:18
@TrejGun please provide minimal reproduction in codesandbox.io

**Comment by TrejGun** [comment] 2022-05-31 07:50
sorry I'm not that interested in the fix

however, my repo is pretty small
you can run it with 2 commands

```
npm i
npm start
```

the bug is in this line
https://github.com/TrejGun/trejgun-nova-poshta-google-maps/blob/master/src/Map/index.tsx#L43

**Comment by mortenmo** [comment] 2022-07-10 07:16
I ran into the same issue. It is a Typescript definition issue. It does work with a `// @ts-ignore` on the line above, but that is not ideal obviously.

**Comment by jchatrny** [comment] 2022-07-13 11:59
For me issue was on `2.10.x` version. Updating to `2.12.0` fixed all of issues

**Comment by JustFly1984** [comment] 2022-07-15 03:15
@jchatrny closing an issue

**Closed by JustFly1984** 2022-07-15 03:15 UTC

**Comment by jantoine1** [comment] 2022-07-23 06:20
I hate to be the bearer of bad news, but this seems broken again in 2.12.1.
