### ISSUE TITLE
Cannot npm install react-google-maps-api in React 18

### ISSUE THREAD

**Issue by Ebukachuqz** [JustFly1984/react-google-maps-api#3001] opened 2022-04-22 23:14 UTC
I Have been tryong to use this great package in react 18 but i keep getting errors when i tryy to NPM INSTALL it.

os: linux

node --version 16

react version 18

@react-google-maps/api version 2.8.1

**Comment by Primajin** [comment] 2022-04-23 13:56
Duplicate of #2978 I guess?

**Comment by Ebukachuqz** [comment] 2022-04-23 19:34
> Duplicate of #2978 I guess?

Not exactly. It was about failed functionalities, here I can't even install the package

**Comment by JustFly1984** [comment] 2022-04-25 03:10
Please post screenshots of errors

**Comment by JustFly1984** [comment] 2022-04-28 04:21
released 2.10.1, please retry

**Closed by JustFly1984** 2022-04-28 04:21 UTC
