### ISSUE TITLE
Map not showing elements anymore with React 18

### ISSUE THREAD

**Issue by marduzca** [JustFly1984/react-google-maps-api#2978] opened 2022-04-03 13:21 UTC
## Please provide an explanation
React 18 was just released and after upgrading I noticed that my map wasn't showing the markers and polygons I rendered anymore. I tried debugging in several ways, but didn't manage to make it work. So I assume that something has to be adjusted in the library to be compatible with React 18.

## Your Environment

os: mac

node --version: 14

react version: 18

webpack version: 4

@react-google-maps/api version: 2.8.0

## How does it behave?
Markers and Polygons are not shown in the map

## How should it behave correctly?
All elements in the map should be visible

**Comment by JustFly1984** [comment] 2022-04-04 21:15
@marduzca 
It is not yet tested with react@18
That will be breaking changes, and we need to release @3.0.0 version
We have gatsby example, and storybook, which first should be updated to support react@18
I'm not talking about docs, which are broken since long time ago...

I will not have time to invest in near future, so if you want, you can make a PR and I will merge it and release new major version

**Comment by merlindru** [comment] 2022-04-05 22:41
I had an issue where markers didn't show on initial render.

Showing the markers conditionally, after the component is rendered, worked:

```ts
const [isMounted, setIsMounted] = useState(false);

useEffect(() => setIsMounted(true), []);

<GoogleMap>
    {isMounted && <Marker position={{ lat: -34.0691357, lng: 18.3802664 }} />}
</GoogleMap>
```

(example is minimal, `<GoogleMap />` is missing loads of props)

**Comment by marduzca** [comment] 2022-04-12 18:30
> I had an issue where markers didn't show on initial render.
> 
> Showing the markers conditionally, after the component is rendered, worked:
> 
> ```ts
> const [isMounted, setIsMounted] = useState(false);
> 
> useEffect(() => setIsMounted(true), []);
> 
> <GoogleMap>
>     {isMounted && <Marker position={{ lat: -34.0691357, lng: 18.3802664 }} />}
> </GoogleMap>
> ```
> 
> (example is minimal, `<GoogleMap />` is missing loads of props)

Thanks for the idea! I tried it out, but it didn't help, I think the problem really is related to the React version

**Comment by marduzca** [comment] 2022-04-25 18:21
@JustFly1984 
Sadly the Upgrade React 18 didn't solve the problem yet :/
Not sure what is happening

**Comment by JustFly1984** [comment] 2022-04-28 04:23
@marduzca can you make a reproduction in codesandbox.io ?

**Comment by brandoniffert** [comment] 2022-04-28 10:46
@JustFly1984 I'm seeing the same thing too when using React 18, but only when using Strict Mode

**Comment by JustFly1984** [comment] 2022-04-28 13:11
@brandoniffert There is several things bad in your code:

- renderMap  - extract to separate component file and wrap `export default memo(MapComponent)`.
- object or array props - you should make it as const or state.
 - you are not using eslint with eslint-plugin-react eslint-plugin-react-hooks eslint-plugin-react-perf
 
 please read more about object reference consistency

**Comment by marduzca** [comment] 2022-04-28 16:10
@JustFly1984 Independently of what could or could not be done better, that doesn't explain why it doesn't work in StrictMode, but works without it. I think it is a good minimal example of what is not working, so let's focus on that topic.

When searching about changes regarding StrictMode in React 18 I only found this:
`With Strict Mode starting in React 18, whenever a component mounts in development, React will simulate immediately unmounting and remounting the component`
Source: https://reactjs.org/docs/strict-mode.html

Could this be causing the trouble?

**Comment by JustFly1984** [comment] 2022-04-29 16:51
@marduzca @brandoniffert  I can't debug myself and have no time to make a reproduction. I guess this is something related to class based component.
Please try new InfoWindowF component and see if it has same issues.

**Comment by marduzca** [comment] 2022-05-03 13:53
@JustFly1984 You don't actually need an API key to test it. The code sandbox from @brandoniffert already allows to debug perfectly.

I think you might be right regarding class vs functional components, because there is no problem rendering the InfoWindowF component and also replacing Marker with MarkerF makes it work in both cases.
See screenshot:
![Screenshot 2022-05-03 at 15 53 00](https://user-images.githubusercontent.com/32594006/166466205-8cd03e2f-28a8-4aa2-855e-092d6b320faf.png)

**Comment by marduzca** [comment] 2022-05-03 15:26
@JustFly1984 
Is `MarkerF` just a functional component version of `Marker`? Can we just do that to all components? I would still need the `Polyline` for example

**Comment by JustFly1984** [comment] 2022-05-03 16:21
@marduzca I'm currently have difficulty to find time to debug the project. I've made multiple F components based on hooks, and looks like majority is working.

To release 3.x we need to male all components as hook based and get rid of class based, and all of it should support react 18 at this point.
I need champions, who are ready to take one or more components left to transform, create the jest test, example in gatsby, and story for storybook.

This library already used by thousands of projects, and I feel like community should step in and provide the support.

I also do not get any income from this open source project.

Google hasn't approached me yet, and did not answered to my issues.

**Comment by hilts-vaughan** [comment] 2022-05-21 04:44
Could it be related to https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-strict-mode? Specifically, the component being unmounted and re-mounted with the same state?

**Comment by JustFly1984** [comment] 2022-05-21 07:41
@hilts-vaughan looks like it does. closing an issue, please use hook based components with react@18+

**Closed by JustFly1984** 2022-05-21 07:41 UTC
Labels: help wanted, good first issue, needs reproduction

**Comment by Saeid-Barzegar** [comment] 2022-06-12 12:47
> @JustFly1984 I'm seeing the same thing too when using React 18, but only when using Strict Mode.
> 
> @marduzca Are you using strict mode? Don't know if it's useful but here's a codesandbox of it with and without strict mode
> 
> https://codesandbox.io/s/react-google-maps-api-forked-8uvb39?file=/src/index.js

Yes, correct!!!! 
it resolved my case 
thanks man

**Comment by abhijayrana** [comment] 2022-08-02 17:13
> 

@marduzca this worked, but im curious about what the difference between marker and markerf is.

**Comment by thalaz** [comment] 2023-11-25 00:14
> > 
> 
> @marduzca this worked, but im curious about what the difference between marker and markerf is.

The difference is that `Marker` is a class component while `MarkerF` is a functional component.

<img width="696" alt="Marker code example" src="https://github.com/JustFly1984/react-google-maps-api/assets/13499938/a7199742-fe4b-4d08-b0cd-aa55f57eea45">

**Comment by Fabioni** [comment] 2024-01-12 07:33
so the answer to that problem is just always using `MarkerF`, `PolylineF` etc.? Feels a bit sketchy. Are there any disadvantages like performance?

**Comment by JustFly1984** [comment] 2024-01-12 08:09
@Fabioni yes use F components for react@17+, there is no performance issues.

**Comment by JustFly1984** [comment] 2024-01-12 08:10
Old components are for backward compatibility.
